In [1]:
import pandas as pd

tracks = []
for i in range(0, 15000, 1000):
    tracks.append(pd.read_csv(f'D:\\million_playlist_dataset_csv\\tracks_{i}-{i+999}.csv',  dtype=str))
tracks = pd.concat(tracks, ignore_index=True)
tracks

artist_name                             track_uri  \
0           Missy Elliott  spotify:track:0UaMYEvWZi0ZqiDOoHU3YI   
1          Britney Spears  spotify:track:6I9VzXrHxO9rA9A5euc8Ak   
2                 Beyoncé  spotify:track:0WqIKmW4BTrj3eJFmnCKMv   
3       Justin Timberlake  spotify:track:1AWQoqb9bSvzTjaLralEkT   
4                  Shaggy  spotify:track:1lzr43nnXAijIGYnCT8M8H   
...                   ...                                   ...   
998404              Aminé  spotify:track:5hTpBe8h35rJ67eAWHQsJx   
998405   Childish Gambino  spotify:track:3kxfsdsCpFgN412fpnW85Y   
998406        Post Malone  spotify:track:6eT7xZZlB2mwyzJ2sUKG6w   
998407        Kodak Black  spotify:track:4Q3N4Ct4zCuIHuZ65E3BD4   
998408             Future  spotify:track:0VgkVdmE4gld66l8iyGjgx   

                                   artist_uri  \
0       spotify:artist:2wIVse2owClT7go1WT98tk   
1       spotify:artist:26dSoYclwsYLMAKD3tpOr4   
2       spotify:artist:6vWDO969PvNqNYHIOW5v0m   
3       spotify:artist:31TPClRtHm23RisEBtV3X7   
4       spotify:artist:5EvFsr3kj42KNv97ZEnqij   
...                                       ...   
998404  spotify:artist:3Gm5F95VdRxW3mqCn8RPBJ   
998405  spotify:artist:73sIBHcqh3Z3NyqHKZ7FOL   
998406  spotify:artist:246dkjvS1zLTtiykXe5h60   
998407  spotify:artist:46SHBwWsqBkxI7EeeBEQG7   
998408  spotify:artist:1RyvyyTE3xzB2ZywiAwp0i   

                                    track_name  \
0       Lose Control feat Ciara  Fat Man Scoop   
1                                        Toxic   
2                                Crazy In Love   
3                               Rock Your Body   
4                                  It Wasnt Me   
...                                        ...   
998404                                Caroline   
998405                                 Redbone   
998406                           White Iverson   
998407                           Tunnel Vision   
998408                                Mask Off   

                                   album_uri duration_ms  \
0       spotify:album:6vV5UrXcfyQD1wu4Qo2I9K      226863   
1       spotify:album:0z7pVBGOD7HCIB7S8eLkLI      198800   
2       spotify:album:25hVFAxTlDvXbx2X2QkUkE      235933   
3       spotify:album:6QPkyl04rXwTGlGlcYaRoW      267266   
4       spotify:album:6NmFmPX56pcLBOFMhIiKvF      227600   
...                                      ...         ...   
998404  spotify:album:3lajefIuUk4SfzqVBSJy8p      209640   
998405  spotify:album:4xnq1L6P551Qcb9gBXNMK7      326933   
998406  spotify:album:5s0rmjP8XOPhP6HhqOhuyC      256533   
998407  spotify:album:5mG8oNkNKM2my7t9ywra96      268186   
998408  spotify:album:17FBoXK1NU2rvJBbzdzw0r      204600   

                                        album_name  
0                                     The Cookbook  
1                                      In The Zone  
2       Dangerously In Love Alben für die Ewigkeit  
3                                        Justified  
4                                         Hot Shot  
...                                            ...  
998404                                Good For You  
998405                              Awaken My Love  
998406                                      Stoney  
998407                           Painting Pictures  
998408                                      FUTURE  

[998409 rows x 7 columns]

In [2]:
tracks.index = tracks['track_uri']
tracks

artist_name  \
track_uri                                                 
spotify:track:0UaMYEvWZi0ZqiDOoHU3YI      Missy Elliott   
spotify:track:6I9VzXrHxO9rA9A5euc8Ak     Britney Spears   
spotify:track:0WqIKmW4BTrj3eJFmnCKMv            Beyoncé   
spotify:track:1AWQoqb9bSvzTjaLralEkT  Justin Timberlake   
spotify:track:1lzr43nnXAijIGYnCT8M8H             Shaggy   
...                                                 ...   
spotify:track:5hTpBe8h35rJ67eAWHQsJx              Aminé   
spotify:track:3kxfsdsCpFgN412fpnW85Y   Childish Gambino   
spotify:track:6eT7xZZlB2mwyzJ2sUKG6w        Post Malone   
spotify:track:4Q3N4Ct4zCuIHuZ65E3BD4        Kodak Black   
spotify:track:0VgkVdmE4gld66l8iyGjgx             Future   

                                                                 track_uri  \
track_uri                                                                    
spotify:track:0UaMYEvWZi0ZqiDOoHU3YI  spotify:track:0UaMYEvWZi0ZqiDOoHU3YI   
spotify:track:6I9VzXrHxO9rA9A5euc8Ak  spotify:track:6I9VzXrHxO9rA9A5euc8Ak   
spotify:track:0WqIKmW4BTrj3eJFmnCKMv  spotify:track:0WqIKmW4BTrj3eJFmnCKMv   
spotify:track:1AWQoqb9bSvzTjaLralEkT  spotify:track:1AWQoqb9bSvzTjaLralEkT   
spotify:track:1lzr43nnXAijIGYnCT8M8H  spotify:track:1lzr43nnXAijIGYnCT8M8H   
...                                                                    ...   
spotify:track:5hTpBe8h35rJ67eAWHQsJx  spotify:track:5hTpBe8h35rJ67eAWHQsJx   
spotify:track:3kxfsdsCpFgN412fpnW85Y  spotify:track:3kxfsdsCpFgN412fpnW85Y   
spotify:track:6eT7xZZlB2mwyzJ2sUKG6w  spotify:track:6eT7xZZlB2mwyzJ2sUKG6w   
spotify:track:4Q3N4Ct4zCuIHuZ65E3BD4  spotify:track:4Q3N4Ct4zCuIHuZ65E3BD4   
spotify:track:0VgkVdmE4gld66l8iyGjgx  spotify:track:0VgkVdmE4gld66l8iyGjgx   

                                                                 artist_uri  \
track_uri                                                                     
spotify:track:0UaMYEvWZi0ZqiDOoHU3YI  spotify:artist:2wIVse2owClT7go1WT98tk   
spotify:track:6I9VzXrHxO9rA9A5euc8Ak  spotify:artist:26dSoYclwsYLMAKD3tpOr4   
spotify:track:0WqIKmW4BTrj3eJFmnCKMv  spotify:artist:6vWDO969PvNqNYHIOW5v0m   
spotify:track:1AWQoqb9bSvzTjaLralEkT  spotify:artist:31TPClRtHm23RisEBtV3X7   
spotify:track:1lzr43nnXAijIGYnCT8M8H  spotify:artist:5EvFsr3kj42KNv97ZEnqij   
...                                                                     ...   
spotify:track:5hTpBe8h35rJ67eAWHQsJx  spotify:artist:3Gm5F95VdRxW3mqCn8RPBJ   
spotify:track:3kxfsdsCpFgN412fpnW85Y  spotify:artist:73sIBHcqh3Z3NyqHKZ7FOL   
spotify:track:6eT7xZZlB2mwyzJ2sUKG6w  spotify:artist:246dkjvS1zLTtiykXe5h60   
spotify:track:4Q3N4Ct4zCuIHuZ65E3BD4  spotify:artist:46SHBwWsqBkxI7EeeBEQG7   
spotify:track:0VgkVdmE4gld66l8iyGjgx  spotify:artist:1RyvyyTE3xzB2ZywiAwp0i   

                                                                  track_name  \
track_uri                                                                      
spotify:track:0UaMYEvWZi0ZqiDOoHU3YI  Lose Control feat Ciara  Fat Man Scoop   
spotify:track:6I9VzXrHxO9rA9A5euc8Ak                                   Toxic   
spotify:track:0WqIKmW4BTrj3eJFmnCKMv                           Crazy In Love   
spotify:track:1AWQoqb9bSvzTjaLralEkT                          Rock Your Body   
spotify:track:1lzr43nnXAijIGYnCT8M8H                             It Wasnt Me   
...                                                                      ...   
spotify:track:5hTpBe8h35rJ67eAWHQsJx                                Caroline   
spotify:track:3kxfsdsCpFgN412fpnW85Y                                 Redbone   
spotify:track:6eT7xZZlB2mwyzJ2sUKG6w                           White Iverson   
spotify:track:4Q3N4Ct4zCuIHuZ65E3BD4                           Tunnel Vision   
spotify:track:0VgkVdmE4gld66l8iyGjgx                                Mask Off   

                                                                 album_uri  \
track_uri                                                                    
spotify:track:0UaMYEvWZi0ZqiDOoHU3YI

In [7]:
#tracks = tracks.groupby(tracks['track_uri'], axis=0)
grouped_tracks = pd.DataFrame(tracks.first())
grouped_tracks['track_uri'] = grouped_tracks.index
grouped_tracks

artist_name  \
track_uri                                                           
spotify:track:000GjfnQc7ggBayDiy1sLW        El Poder De Zacatecas   
spotify:track:000JBgYWfJQqdFaRqu2n3f                     Joe Pass   
spotify:track:000ULyVqUhqnAyA0Um3MEH                  Arms Akimbo   
spotify:track:000VZqvXwT0YNqKk7iG2GS             The Ghost Inside   
spotify:track:000mA0etY38nKdvf1N04af                  The Coronas   
...                                                           ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58              Hippie Sabotage   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn  Kimberly and Alberto Rivera   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J                  DJ Punisher   
spotify:track:7zzmpRP0WkYge45l6LTQ8i            Jason Schwartzman   
spotify:track:7zzptITgTKf4HpJM8ye47v               Compay Segundo   

                                                                 artist_uri  \
track_uri                                                                     
spotify:track:000GjfnQc7ggBayDiy1sLW  spotify:artist:3n3k65ADvmwixFITCnC78C   
spotify:track:000JBgYWfJQqdFaRqu2n3f  spotify:artist:4DuZTASH5eSyd0K73W6fuZ   
spotify:track:000ULyVqUhqnAyA0Um3MEH  spotify:artist:5vuEKqaoIXJjZWOGxfXCzN   
spotify:track:000VZqvXwT0YNqKk7iG2GS  spotify:artist:6kQB2RN7WwryMdJ1MoQh1E   
spotify:track:000mA0etY38nKdvf1N04af  spotify:artist:2tppd6KkhK4ULAd217Ecq1   
...                                                                     ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58  spotify:artist:4dM6NDYSfLcspt8GLoT5aE   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn  spotify:artist:5L0eKYl8JfgYBNnz8wBr7i   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J  spotify:artist:3qBNbuwNIZVqkR4Lp3LgC1   
spotify:track:7zzmpRP0WkYge45l6LTQ8i  spotify:artist:7iihQll6y9O8Iee7D1uEcb   
spotify:track:7zzptITgTKf4HpJM8ye47v  spotify:artist:2wpr4ILskkRzPBGodmbMs1   

                                                            track_name  \
track_uri                                                                
spotify:track:000GjfnQc7ggBayDiy1sLW                       Abeja Miope   
spotify:track:000JBgYWfJQqdFaRqu2n3f                        Lil Darlin   
spotify:track:000ULyVqUhqnAyA0Um3MEH                            Simmer   
spotify:track:000VZqvXwT0YNqKk7iG2GS                             Mercy   
spotify:track:000mA0etY38nKdvf1N04af  If I Gave Myself To Someone Else   
...                                                                ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58                  Quit Wastin Time   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn                  Spirit to Spirit   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J                       BAD  BOUJEE   
spotify:track:7zzmpRP0WkYge45l6LTQ8i                Lets Go Fly a Kite   
spotify:track:7zzptITgTKf4HpJM8ye47v              Me Diras Que Sabroso   

                                                                 album_uri  \
track_uri                                                                    
spotify:track:000GjfnQc7ggBayDiy1sLW  spotify:album:18XgaglyP4IDDZQFS3yQBW   
spotify:track:000JBgYWfJQqdFaRqu2n3f  spotify:album:2zm8AkHjOhwdvnj8NSVg6g   
spotify:track:000ULyVqUhqnAyA0Um3MEH  spotify:album:23s2PFr0MCiFAf8FlpHElU   
spotify:track:000VZqvXwT0YNqKk7iG2GS  spotify:album:75kQjmcR1YnIrBwVW1s4G1   
spotify:track:000mA0etY38nKdvf1N04af  spotify:album:662PiU3dRsilN0Gp87IiSF   
...                                                                    ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58  spotify:album:2VmLk5bAd5QjLtX7cHm594   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn  spotify:album:4oPuRYCPPA0MAtP0XP7kvJ   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J  spotify:album:4itoh8aZG9ajLV2NnQ9AnC   
spotify:track:7zzmpRP0WkYge45l6LTQ8i  spotify:album:6Es5vDJhZYK6orHqMDCy0w   
spotify:track:7zzptITgTKf4HpJM8ye47v  spotify:album:1lnqHuxkVGegpTyxxdDYY8   

                                     duration_ms  \
track_uri                                          
spotify:track:000GjfnQc7ggBayDiy1sLW      1403

In [8]:
import csv

with open('D:\\extracted_features\\all_tracks.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)
    
    writer.writerow(grouped_tracks.columns)
    
    writer.writerows(grouped_tracks.values)

In [4]:
for uri in ['artist_uri', 'album_uri']:
    grouped_tracks[uri] = [value.split(':')[2] for value in grouped_tracks[uri].values]
    
grouped_tracks['track_uri'] =  [value.split(':')[2] for value in grouped_tracks.index]
grouped_tracks

artist_name  \
track_uri                                                           
spotify:track:000GjfnQc7ggBayDiy1sLW        El Poder De Zacatecas   
spotify:track:000JBgYWfJQqdFaRqu2n3f                     Joe Pass   
spotify:track:000ULyVqUhqnAyA0Um3MEH                  Arms Akimbo   
spotify:track:000VZqvXwT0YNqKk7iG2GS             The Ghost Inside   
spotify:track:000mA0etY38nKdvf1N04af                  The Coronas   
...                                                           ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58              Hippie Sabotage   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn  Kimberly and Alberto Rivera   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J                  DJ Punisher   
spotify:track:7zzmpRP0WkYge45l6LTQ8i            Jason Schwartzman   
spotify:track:7zzptITgTKf4HpJM8ye47v               Compay Segundo   

                                                  artist_uri  \
track_uri                                                      
spotify:track:000GjfnQc7ggBayDiy1sLW  3n3k65ADvmwixFITCnC78C   
spotify:track:000JBgYWfJQqdFaRqu2n3f  4DuZTASH5eSyd0K73W6fuZ   
spotify:track:000ULyVqUhqnAyA0Um3MEH  5vuEKqaoIXJjZWOGxfXCzN   
spotify:track:000VZqvXwT0YNqKk7iG2GS  6kQB2RN7WwryMdJ1MoQh1E   
spotify:track:000mA0etY38nKdvf1N04af  2tppd6KkhK4ULAd217Ecq1   
...                                                      ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58  4dM6NDYSfLcspt8GLoT5aE   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn  5L0eKYl8JfgYBNnz8wBr7i   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J  3qBNbuwNIZVqkR4Lp3LgC1   
spotify:track:7zzmpRP0WkYge45l6LTQ8i  7iihQll6y9O8Iee7D1uEcb   
spotify:track:7zzptITgTKf4HpJM8ye47v  2wpr4ILskkRzPBGodmbMs1   

                                                            track_name  \
track_uri                                                                
spotify:track:000GjfnQc7ggBayDiy1sLW                       Abeja Miope   
spotify:track:000JBgYWfJQqdFaRqu2n3f                        Lil Darlin   
spotify:track:000ULyVqUhqnAyA0Um3MEH                            Simmer   
spotify:track:000VZqvXwT0YNqKk7iG2GS                             Mercy   
spotify:track:000mA0etY38nKdvf1N04af  If I Gave Myself To Someone Else   
...                                                                ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58                  Quit Wastin Time   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn                  Spirit to Spirit   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J                       BAD  BOUJEE   
spotify:track:7zzmpRP0WkYge45l6LTQ8i                Lets Go Fly a Kite   
spotify:track:7zzptITgTKf4HpJM8ye47v              Me Diras Que Sabroso   

                                                   album_uri duration_ms  \
track_uri                                                                  
spotify:track:000GjfnQc7ggBayDiy1sLW  18XgaglyP4IDDZQFS3yQBW      140360   
spotify:track:000JBgYWfJQqdFaRqu2n3f  2zm8AkHjOhwdvnj8NSVg6g      227626   
spotify:track:000ULyVqUhqnAyA0Um3MEH  23s2PFr0MCiFAf8FlpHElU      251000   
spotify:track:000VZqvXwT0YNqKk7iG2GS  75kQjmcR1YnIrBwVW1s4G1      256478   
spotify:track:000mA0etY38nKdvf1N04af  662PiU3dRsilN0Gp87IiSF      214506   
...                                                      ...         ...   
spotify:track:7zzLt6Z9y7jMvXnEg00n58  2VmLk5bAd5QjLtX7cHm594       69773   
spotify:track:7zzTO3iXxR1kXhkKPqRpNn  4oPuRYCPPA0MAtP0XP7kvJ      435200   
spotify:track:7zzjrF4VOGmhmzkFqjuW9J  4itoh8aZG9ajLV2NnQ9AnC      131137   
spotify:track:7zzmpRP0WkYge45l6LTQ8i  6Es5vDJhZYK6orHqMDCy0w      115000   
spotify:track:7zzptITgTKf4HpJM8ye47v  1lnqHuxkVGegpTyxxdDYY8      215813   

                                                          album_name  \
track_uri                                                              
spotify:track:000GjfnQc7ggBayDiy1sLW                 Y las Mariposas   
spotify:track:000JBgYWfJQqdFaRqu2n3f                        Portrait   
spotify:track:000ULyVqUhqnAyA0Um3MEH                       Vignettes   
spotify:tra

In [5]:
tracks_joined = [' '.join([str(item).lower() for item in row]) for row in grouped_tracks.values]
print(len(tracks_joined[0]))
tracks_joined[:10]

125


['el poder de zacatecas 3n3k65advmwixfitcnc78c abeja miope 18xgaglyp4iddzqfs3yqbw 140360 y las mariposas 000gjfnqc7ggbaydiy1slw',
 'joe pass 4duztash5esyd0k73w6fuz lil darlin 2zm8akhjohwdvnj8nsvg6g 227626 portrait 000jbgywfjqqdfarqu2n3f',
 'arms akimbo 5vuekqaoixjjzwogxfxczn simmer 23s2pfr0mcifaf8flphelu 251000 vignettes 000ulyvquhqnaya0um3meh',
 'the ghost inside 6kqb2rn7wwrymdj1moqh1e mercy 75kqjmcr1ynirbwvw1s4g1 256478 dear youth 000vzqvxwt0ynqkk7ig2gs',
 'the coronas 2tppd6kkhk4ulad217ecq1 if i gave myself to someone else 662piu3drsiln0gp87iisf 214506 the long way 000ma0ety38nkdvf1n04af',
 'zayn 5zsfi1h6hidqrw2ti0hz81 still got time 2kguetgnkloylinkrje47g 188490 still got time 000xql6tznljzirtigxqsl',
 'bombay bicycle club 3pte9iajtkwns3mxpnqljv its alright now 5okwooliuowmg6aorva9hl 249946 so long see you tomorrow 0010mzpccwlpwobibsjoac',
 'iceage 03hloxqryyxo3ectp3eebu on my fingers 2zfpmxjsyl4hnmy1hzcfie 314000 plowing into the field of love 0012giwzfurw8rjidnptas',
 'the front 

In [6]:
from ipynb.fs.full.bert_helper import create_raw_input, pull_bert, get_max_lengths, bert_encode

bert_layer, tokenizer = pull_bert('https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-256_A-4/2')
X = bert_encode(tracks_joined, tokenizer, 140)

In [7]:
X

{'input_word_ids': <tf.Tensor: shape=(218129, 140), dtype=int32, numpy=
 array([[  101,  3449, 17491, ...,     0,     0,     0],
        [  101,  3533,  3413, ...,     0,     0,     0],
        [  101,  2608, 17712, ...,     0,     0,     0],
        ...,
        [  101,  6520, 16385, ...,     0,     0,     0],
        [  101,  4463, 16756, ...,     0,     0,     0],
        [  101,  4012,  4502, ...,     0,     0,     0]])>,
 'input_mask': <tf.Tensor: shape=(218129, 140), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]])>,
 'input_type_ids': <tf.Tensor: shape=(218129, 140), dtype=int32, numpy=
 array([[0, 1, 1, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 1, 1, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0]])>}

In [8]:
import tensorflow as tf

input_word_ids = tf.keras.layers.Input(shape=(140,), dtype=tf.int32, name="input_word_ids")
input_mask = tf.keras.layers.Input(shape=(140,), dtype=tf.int32, name="input_mask")
input_type_ids = tf.keras.layers.Input(shape=(140,), dtype=tf.int32, name="input_type_ids")

bert_input = {
    'input_word_ids': input_word_ids,
    'input_mask': input_mask,
    'input_type_ids': input_type_ids
}

outputs = bert_layer(bert_input)
pooled_output = outputs['pooled_output']
sequence_output = outputs['sequence_output']
model = tf.keras.Model(
    inputs={
        'input_word_ids': input_word_ids,
        'input_mask': input_mask,
        'input_type_ids': input_type_ids
    },
    outputs=pooled_output
)

model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_mask (InputLayer)         [(None, 140)]        0                                            
__________________________________________________________________________________________________
input_type_ids (InputLayer)     [(None, 140)]        0                                            
__________________________________________________________________________________________________
input_word_ids (InputLayer)     [(None, 140)]        0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'default': (None, 2 9591041     input_mask[0][0]                 
                                                                 input_type_ids[0][0]         

In [9]:
extracted_features = model.predict(X)
extracted_features

array([[ 0.46477666, -0.12568407,  0.71570975, ...,  0.21680754,
         0.5808984 ,  0.05902258],
       [ 0.565548  ,  0.04826403, -0.6356013 , ...,  0.6001719 ,
         0.87655157, -0.08291348],
       [ 0.09728966, -0.0256166 , -0.6402798 , ...,  0.46544576,
         0.7569948 ,  0.0141486 ],
       ...,
       [ 0.241034  , -0.12221943, -0.47354925, ...,  0.3981859 ,
         0.9111046 ,  0.147198  ],
       [ 0.6978688 , -0.04433439, -0.20988965, ...,  0.7239238 ,
         0.8868694 , -0.06425013],
       [ 0.63090897, -0.10355177, -0.0375589 , ...,  0.908723  ,
         0.9495339 ,  0.09332509]], dtype=float32)

In [10]:
import numpy as np
#track_embeddings = [np.insert(np.array(feature, dtype=str), 0, 'spotify:track:'+track) for track, feature in zip(grouped_tracks['track_uri'], extracted_features)]
#track_embeddings

new_arr=[]
for i in range(0, len(extracted_features)):
    curr_arr = []
    curr_arr.append(grouped_tracks.index[i])
    [curr_arr.append(value) for value in extracted_features[i]]
    new_arr.append(curr_arr)
print(new_arr)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [11]:
print(new_arr[0:10])

[['spotify:track:000GjfnQc7ggBayDiy1sLW', 0.46477666, -0.12568407, 0.71570975, 0.3580843, 0.3037615, 0.95401096, -0.29585916, 0.028331315, -0.495248, -0.03342819, 0.9499019, 0.82084453, 0.030651888, 0.84119695, 0.97026634, 0.02544933, -0.99894553, -0.05620575, 0.96776, 0.90305185, 0.23332356, 0.51674503, -0.98919415, -0.49383393, -0.8613887, 0.95816785, 0.06690943, -0.8955123, -0.44557378, 0.78702796, 0.013252125, -0.14707059, 0.9975456, -0.24902289, 0.21619648, 0.108619876, 0.9952953, -0.0049560633, 0.71937764, 0.2488296, 0.90285623, 0.96676475, -0.9984164, -0.067294374, -0.933669, 0.9960105, -0.7878734, -0.21995938, 0.86253226, 0.64429456, 0.98638755, -0.99539554, 0.98092747, -0.23363125, -0.84628683, 0.8079946, -0.9517125, -0.98933864, -0.8214557, -0.96333516, 0.09301621, 0.15179025, -0.3339529, -0.4327474, -0.124015816, -0.18083625, 0.9435463, 0.9613151, 0.84355754, 0.23460843, -0.99661964, -0.12768382, 0.98248005, 0.08107697, 0.7527755, 0.9277988, 0.0004649813, -0.49226195, -0.081

In [12]:
import csv

csv_headers = ['track_uri']
[csv_headers.append(i) for i in range(0, 256)]

with open('D:\\extracted_features\\tracks_256_full.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)
    
    writer.writerow(csv_headers)
    
    writer.writerows(new_arr)

In [49]:
grouped_tracks.index
all_values = []
for value in grouped_tracks.index.values:
    all_values.append([str(value)])

with open('D:\\extracted_features\\tracks_uris.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)
    
    writer.writerow(['uri'])
    
    writer.writerows(all_values)

In [42]:
grouped_tracks.index.values[0]

'spotify:track:000GjfnQc7ggBayDiy1sLW'

In [2]:
import pandas as pd
uris = pd.read_csv(f'D:\\extracted_features\\tracks_uris.csv',  dtype=str)
uris

uri
0       spotify:track:000GjfnQc7ggBayDiy1sLW
1       spotify:track:000JBgYWfJQqdFaRqu2n3f
2       spotify:track:000ULyVqUhqnAyA0Um3MEH
3       spotify:track:000VZqvXwT0YNqKk7iG2GS
4       spotify:track:000mA0etY38nKdvf1N04af
...                                      ...
218124  spotify:track:7zzLt6Z9y7jMvXnEg00n58
218125  spotify:track:7zzTO3iXxR1kXhkKPqRpNn
218126  spotify:track:7zzjrF4VOGmhmzkFqjuW9J
218127  spotify:track:7zzmpRP0WkYge45l6LTQ8i
218128  spotify:track:7zzptITgTKf4HpJM8ye47v

[218129 rows x 1 columns]

In [ ]:
track_embeddings = pd.read_csv(f'D:\\extracted_features\\tracks.csv',  dtype=str)
track_embeddings